#!/bin/sh

# Host and TCP port for FASTCGI-Listener (default: localhost:9000)
FCGI_HOST=127.0.0.1
FCGI_PORT=8001

# Environment variables, which are processed by PHP
PHP_FCGI_CHILDREN=4
PHP_FCGI_MAX_REQUESTS=1000
export PHP_FCGI_CHILDREN PHP_FCGI_MAX_REQUESTS

DAEMON=/usr/bin/php-cgi
PHP_CONFIG_FILE=/etc/php5/cgi/php.ini
DAEMON_ARGS="-q -b $FCGI_HOST:$FCGI_PORT -c $PHP_CONFIG_FILE"

exec setuidgid www-data $DAEMON $DAEMON_ARGS
